### ISSUE TITLE
make search work

### ISSUE THREAD

**Issue by martinantonmueller** [hermann-bahr/bahr-textverzeichnis-static#2]
search should access all //text() – i.e. be a true full text search.

**Comment by csae8092** [comment]
all text nodes -> full text
date -> title type iso-date
facet biblStruct type

**Comment by csae8092** [comment]
wip: https://github.com/hermann-bahr/bahr-textverzeichnis-static/commit/2ca13edfd0d93e2f55cbcce1f49701855c16d7f0
